### ISSUE TITLE
Cancel button for edit action

### ISSUE THREAD

**Issue by celsosantarosa** [glauberramos/firedeaz#17]
Given that the user did some changes on the card text, but, because of any reason, the user decided to give up on the changes, She/He has to undo all the changes before click on the done button. A cancel button will allow them to give up on their changes at any time, disregarding their changes.

**Comment by glauberramos** [comment]
This is hard to do right now because we are updating the changes automatically, that means any change is shown to the other users when someone is typing. This gives a very nice experience because everything is live. In order to implement a cancel button we would have to disable this behaviour and I don't think it's very necessary right now.
